point_cloud_topic: "/points"
robot_pose_topic: "/robot_state/pose"
parent_frame_id: "/map"
base_frame_id: "/robot"
robot_pose_cache_size: 200
track_point_frame_id: "/robot"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0