scan_filter_chain:
- name: shadows
  type: ScanShadowsFilter
  params:
    min_angle: 8
    max_angle: 172
    neighbors: 10
    window: 1

- name: range_filter
  type: LaserScanRangeFilter
  params:
    lower_threshold: 0.3
    upper_threshold: 35

#- name: dark_shadows
#  type: LaserScanIntensityFilter
#  params: 
#    lower_threshold: 0
#    upper_threshold: 10000

